export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_VIDEO_URLS = 'CHANGE_VIDEO_URLS';
export const ADD_TO_RECENT_KEYWORDS = 'ADD_TO_RECENT_KEYWORDS';
export const ADD_TO_WATCHED_VIDEOS = 'ADD_TO_WATCHED_VIDEOS';
export const UPDATE_RECORDED_VIDEOS = 'UPDATE_RECORDED_VIDEOS';
